#: Aurora Night
#: Custom Kitty Theme

# Background / Foreground
background              #0b1220
foreground              #d8dee9

# Cursor
cursor                  #7dd3fc
cursor_text_color       #0b1220

# Selection
selection_background    #334155
selection_foreground    #f8fafc

# URL color
url_color               #38bdf8

# Window border
active_border_color     #7c3aed
inactive_border_color   #1e293b
bell_border_color       #ef4444

# Tabs
active_tab_background   #7c3aed
active_tab_foreground   #ffffff

inactive_tab_background #1e293b
inactive_tab_foreground #94a3b8

tab_bar_background      #0b1220

# Marks
mark1_background        #22c55e
mark1_foreground        #000000

mark2_background        #f59e0b
mark2_foreground        #000000

mark3_background        #ef4444
mark3_foreground        #ffffff

# ANSI Colors

# Black
color0  #1e293b
color8  #475569

# Red
color1  #f87171
color9  #fb7185

# Green
color2  #4ade80
color10 #22c55e

# Yellow
color3  #facc15
color11 #fbbf24

# Blue
color4  #60a5fa
color12 #38bdf8

# Magenta
color5  #c084fc
color13 #a78bfa

# Cyan
color6  #22d3ee
color14 #67e8f9

# White
color7  #e2e8f0
color15 #ffffff
