# Reload configuration
map ctrl+shift+r load_config_file

# Tabs
map ctrl+shift+t new_tab
map ctrl+shift+w close_tab
map ctrl+tab next_tab
map ctrl+shift+tab previous_tab

# Splits
map ctrl+shift+enter launch --location=hsplit
# map ctrl+shift+v launch --location=vsplit

# Pane navigation
map alt+h neighboring_window left
map alt+j neighboring_window down
map alt+k neighboring_window up
map alt+l neighboring_window right

# Pane resizing
map ctrl+alt+h resize_window narrower
map ctrl+alt+l resize_window wider
map ctrl+alt+k resize_window taller
map ctrl+alt+j resize_window shorter
