# Main configuration

include conf/fonts.conf
include conf/appearance.conf
include conf/colors.conf
include conf/performance.conf
include conf/tabs.conf
include conf/mouse.conf
include conf/clipboard.conf
include conf/shell.conf
include conf/layout.conf
include conf/keybindings.conf
