# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format = 'using [$hostname](bold italic blue) '
trim_at = "."
disabled = false

[character]
success_symbol = "[󰘧](bold green)"
error_symbol = "[✗](bold red)"

[directory]
read_only = " "
truncation_length = 10
style = "bold yellow"

[cmd_duration]
min_time = 4
show_milliseconds = false
disabled = false
style = "bold italic red"
